/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as accessblity from "./Accessblity";
export type { accessblity };
import type * as binders from "./Binders";
export type { binders };
import type * as registerable from "./Registerable";
export type { registerable };
