/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OwnableContract,
  OwnableContractInterface,
} from "../../../../../../../../src/solidity/contracts/Core/Objective/Accessblity/Ownablity/OwnableContract";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "AdminAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "AdminRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousSuperAdmin",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newSuperAdmin",
        type: "address",
      },
    ],
    name: "SuperAdminChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSuperAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class OwnableContract__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableContractInterface {
    return new Interface(_abi) as OwnableContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OwnableContract {
    return new Contract(address, _abi, runner) as unknown as OwnableContract;
  }
}
