/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface OwnableContractContract
  extends Truffle.Contract<OwnableContractInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<OwnableContractInstance>;
}

export interface AdminAdded {
  name: "AdminAdded";
  args: {
    admin: string;
    0: string;
  };
}

export interface AdminRemoved {
  name: "AdminRemoved";
  args: {
    admin: string;
    0: string;
  };
}

export interface SuperAdminChanged {
  name: "SuperAdminChanged";
  args: {
    previousSuperAdmin: string;
    newSuperAdmin: string;
    0: string;
    1: string;
  };
}

type AllEvents = AdminAdded | AdminRemoved | SuperAdminChanged;

export interface OwnableContractInstance extends Truffle.ContractInstance {
  getOwner(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getSuperAdmin(txDetails?: Truffle.TransactionDetails): Promise<string>;

  isAdmin(
    user: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    getOwner(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getSuperAdmin(txDetails?: Truffle.TransactionDetails): Promise<string>;

    isAdmin(
      user: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
