/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface StatusableContract
  extends Truffle.Contract<StatusableInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<StatusableInstance>;
}

export interface Locked {
  name: "Locked";
  args: {
    untilBlock: BN;
    0: BN;
  };
}

export interface Paused {
  name: "Paused";
  args: {};
}

export interface Unlocked {
  name: "Unlocked";
  args: {};
}

export interface Unpaused {
  name: "Unpaused";
  args: {};
}

type AllEvents = Locked | Paused | Unlocked | Unpaused;

export interface StatusableInstance extends Truffle.ContractInstance {
  isLocked(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  isPaused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  methods: {
    isLocked(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    isPaused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
