/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiSendOnlyCallSol from "./MultiSendOnlyCall.sol";
export type { multiSendOnlyCallSol };
export type { Executor } from "./Executor";
export type { MultiSend } from "./MultiSend";
