/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stake from "./Stake";
export type { stake };
export type { BaseModule } from "./BaseModule";
