/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseRegistry__factory } from "./BaseRegistry__factory";
export { Registerable__factory } from "./Registerable__factory";
