/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as geteway from "./Geteway";
export type { geteway };
import type * as space from "./Space";
export type { space };
import type * as vault from "./Vault";
export type { vault };
