/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { BaseDeployer, BaseDeployerInterface } from "../BaseDeployer";

const _abi = [
  {
    type: "function",
    name: "_computeAddress",
    inputs: [
      {
        name: "_bytecode",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_salt",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deploy",
    inputs: [
      {
        name: "_bytecode",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_salt",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initiateDeployment",
    inputs: [
      {
        name: "_bytecode",
        type: "bytes",
        internalType: "bytes",
      },
      {
        name: "_salt",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ContractDeployed",
    inputs: [
      {
        name: "deployer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "contractAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061030a8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063204f09eb146100465780634af63f02146100755780637e711c0614610088575b600080fd5b61005961005436600461021f565b61009b565b6040516001600160a01b03909116815260200160405180910390f35b61005961008336600461021f565b6100f7565b61005961009636600461021f565b61010a565b8151602092830120604080516001600160f81b0319818601523060601b6bffffffffffffffffffffffff191660218201526035810193909352605580840192909252805180840390920182526075909201909152805191012090565b6000610103838361009b565b9392505050565b60006101038383600080835160000361016a5760405162461bcd60e51b815260206004820152601760248201527f42797465636f6465206c656e677468206973207a65726f00000000000000000060448201526064015b60405180910390fd5b828451602086016000f590506001600160a01b0381166101cc5760405162461bcd60e51b815260206004820152601960248201527f4661696c656420746f206465706c6f7920636f6e7472616374000000000000006044820152606401610161565b6040516001600160a01b0382169033907f33c981baba081f8fd2c52ac6ad1ea95b6814b4376640f55689051f658472968890600090a39392505050565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561023257600080fd5b823567ffffffffffffffff8082111561024a57600080fd5b818501915085601f83011261025e57600080fd5b81358181111561027057610270610209565b604051601f8201601f19908116603f0116810190838211818310171561029857610298610209565b816040528281528860208487010111156102b157600080fd5b82602086016020830137600060209382018401529896909101359650505050505056fea26469706673582212202cc7b75911780c65b1fe891e66b147330ee766350b4ea3d9df1c044b7dfbe84964736f6c63430008190033";

type BaseDeployerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BaseDeployerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BaseDeployer__factory extends ContractFactory {
  constructor(...args: BaseDeployerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BaseDeployer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): BaseDeployer__factory {
    return super.connect(runner) as BaseDeployer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BaseDeployerInterface {
    return new Interface(_abi) as BaseDeployerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BaseDeployer {
    return new Contract(address, _abi, runner) as unknown as BaseDeployer;
  }
}
