/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MultiSend, MultiSendInterface } from "../MultiSend";

const _abi = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "multiSend",
    inputs: [
      {
        name: "transactions",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
] as const;

const _bytecode =
  "0x60a0604052348015600f57600080fd5b503060805260805161025c61002e60003960006042015261025c6000f3fe60806040526004361061001e5760003560e01c80638d80ff0a14610023575b600080fd5b610036610031366004610175565b610038565b005b6001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001630036100cd5760405162461bcd60e51b815260206004820152603060248201527f4d756c746953656e642073686f756c64206f6e6c792062652063616c6c65642060448201526f1d9a584819195b1959d85d1958d85b1b60821b606482015260840160405180910390fd5b805160205b8181101561015a57828101805160018201516015830151603584015160f89390931c9360609290921c8015300217929091605501600085801561011c576001811461012c57610137565b6000808585888a5af19150610137565b6000808585895af491505b5080610147573d6000803e3d6000fd5b50508060550185019450505050506100d2565b505050565b634e487b7160e01b600052604160045260246000fd5b60006020828403121561018757600080fd5b813567ffffffffffffffff8082111561019f57600080fd5b818401915084601f8301126101b357600080fd5b8135818111156101c5576101c561015f565b604051601f8201601f19908116603f011681019083821181831017156101ed576101ed61015f565b8160405282815287602084870101111561020657600080fd5b82602086016020830137600092810160200192909252509594505050505056fea2646970667358221220cb3dbc9a66295acf5a2fb067d0261eeb85927e097bd16700cf891c453b0b380764736f6c63430008190033";

type MultiSendConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MultiSendConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MultiSend__factory extends ContractFactory {
  constructor(...args: MultiSendConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MultiSend & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MultiSend__factory {
    return super.connect(runner) as MultiSend__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MultiSendInterface {
    return new Interface(_abi) as MultiSendInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MultiSend {
    return new Contract(address, _abi, runner) as unknown as MultiSend;
  }
}
