/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Statusable, StatusableInterface } from "../Statusable";

const _abi = [
  {
    type: "function",
    name: "getOwner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isAdmin",
    inputs: [
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isLocked",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPaused",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AdminStatusChanged",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "status",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Locked",
    inputs: [
      {
        name: "untilBlock",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerChanged",
    inputs: [
      {
        name: "oldOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "StatusableInitialized",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SuperAdminChanged",
    inputs: [
      {
        name: "oldSuperAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newSuperAdmin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unlocked",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [],
    anonymous: false,
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50600080546001600160a01b03191633179055610163806100316000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806324d7806c14610051578063893d20e814610079578063a4e2d63414610094578063b187bd261461009c575b600080fd5b61006461005f3660046100fd565b6100a7565b60405190151581526020015b60405180910390f35b6000546040516001600160a01b039091168152602001610070565b6100646100e1565b60055460ff16610064565b6001600160a01b03811660009081526002602052604081205460ff16806100db57506001546001600160a01b038381169116145b92915050565b60035460009060ff1680156100f857506004544311155b905090565b60006020828403121561010f57600080fd5b81356001600160a01b038116811461012657600080fd5b939250505056fea2646970667358221220b2265d0a0d2a42f1a92add31066f22d626418c0e64af744cfbf13852b1807c8864736f6c63430008190033";

type StatusableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StatusableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Statusable__factory extends ContractFactory {
  constructor(...args: StatusableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Statusable & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Statusable__factory {
    return super.connect(runner) as Statusable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StatusableInterface {
    return new Interface(_abi) as StatusableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Statusable {
    return new Contract(address, _abi, runner) as unknown as Statusable;
  }
}
